accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path("userLogin", views.userLogin, name="userLogin"),
    path('logged_out/', views.userLoggedout, name='userLoggedout'),
    path("profile/", views.profile, name="profile"),
    path("profile/edit", views.profile_edit, name="edit_profile"),
    path("signup", views.signup, name="signup"),

]

src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class Profile(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneNumber = models.CharField(max_length=15, blank=True ,null=True, default='')
    description = models.TextField(max_length=500, blank=True ,null=True, default='')
    userphoto   = models.ImageField(upload_to='userImage/', blank=True ,null=True)
    def __str__(self):
        return str(self.user)

##### Create User Profile By Signals ######

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

store/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.


class Book(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", args=[str(self.id)])

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    class Meta:
        model  = User
        fields = [ 'first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        help_texts = {
            'first_name': None,
            'last_name': None,
            'username': None,
            'email': None,
            'password1': None

        }

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

class InstructorSignupForm(UserCreationForm):
    class Meta:
        model  = User
        fields = [ 'first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'is_staff']
        help_texts = {
            'first_name': None,
            'last_name': None,
            'username': None,
            'email': None,
            'password1': None,

        }


    def __init__(self, *args, **kwargs):
        super(InstructorSignupForm, self).__init__(*args, **kwargs)

        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''


class UserForm(forms.ModelForm):
    class Meta:
        model  = User
        fields = ['first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model  = Profile
        fields = ['phoneNumber', 'userphoto' ]

accounts/views.py
from django.shortcuts import render, redirect, reverse
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import *
from .forms import *

# Create your views here.


def userLogin(request):
    if request.method == "POST":
        username = request.POST.get('name')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("blog:post_list")
        else:
            messages.warning(request, 'Username or password is wrong.')
    return render(request, 'accounts/login.html')


def profile(request):
    profile = Profile.objects.get(user=request.user)
    context = {
        'profile': profile
    }
    return render(request, 'accounts/profile.html', context)


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        userForm = UserForm(request.POST, instance=request.user)
        profileForm = ProfileForm(
            request.POST, request.FILES, instance=profile)
        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            myprofile = profileForm.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))

    else:
        userForm = UserForm(instance=request.user)
        profileForm = ProfileForm(instance=profile)

    context = {
        "userForm": userForm,
        "profileForm": profileForm,
    }
    return render(request, 'accounts/profile_edit.html', context)


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/accounts/profile/')
    else:
        form = SignupForm()

    context = {"form": form}
    return render(request, 'accounts/register.html', context)


def userLoggedout(request):
    logout(request)
    return redirect('blog:post_list')

store/views.py
from django.shortcuts import render
from django.views.generic import ListView

# Create your views here.

accounts/templates/accounts/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<section class="hero-wrap hero-wrap-2 degree-right" style="background-image: url({% static 'images/bg_2.jpg'%})"
  data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-end">
      <div class="col-md-9 ftco-animate pb-5 mb-5">
        <p class="breadcrumbs">
          <span class="mr-2"><a href="index.html">Home <i class="fa fa-chevron-right"></i></a></span>
          <span>Blog <i class="fa fa-chevron-right"></i></span>
        </p>
        <h1 class="mb-3 bread">Blog</h1>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section">
  <div class="container">
    <div class="row d-flex">

      <form method="POST" class="signup-form">
        {% csrf_token %}
        {% for message in messages %}
        <h3 style="color:red">{{ message }}</h3>
        <br>
        {% endfor %}
        <div class="form-group">
          <label class="label" for="username">Username</label>
          <input type="text" class="form-control" id="name" name="name" placeholder="Username" />
        </div>

        <div class="form-group">
          <label class="label" for="password">Password</label>
          <input type="password" class="form-control" id="password" name="password" placeholder="Password" />
        </div>
        <div class="form-group d-flex justify-content-end mt-4">
          <a href="{% url 'accounts:signup' %}" style="margin-right: 9rem;">Create An Account</a>
          <input type="submit" class="btn btn-primary submit" name="submit" value="login">
        </div>
      </form>


    </div>

    <div class="row mt-5 pb-5">
      <div class="col text-center">
        <div class="block-27">
          <ul>
            <li><a href="#">&lt;</a></li>
            <li class="active"><span>1</span></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&gt;</a></li>
          </ul>

        </div>
      </div>
    </div>
  </div>

</section>
{% endblock%}

accounts/templates/accounts/profile.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <style>
    body{

    color: #1a202c;
    text-align: left;
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
    </style>

        
<section
  class="hero-wrap hero-wrap-2 degree-right"
  style="background-image: url({% static 'images/bg_2.jpg'%})"
  data-stellar-background-ratio="0.5"
>
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-end">
      <div class="col-md-9 ftco-animate pb-5 mb-5">
  
        <h1 class="mb-3 bread">Welcome {{ profile.user.username}}</h1>
        <br>
          <br>
            <br>
      </div>
    </div>
  </div>
</section>
    <div class="container">
    <div class="main-body">

          <!-- Breadcrumb -->
          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{% if profile.userphoto %} {{ profile.userphoto.url }} {% else %} {% static 'images/no_image.png' %} {% endif %}" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ profile.user.first_name}} {{ profile.user.last_name }}</h4>
                      <p class="text-secondary mb-1">{{ profile.description}}</p>
                        <a class="btn btn-primary" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">First Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ profile.user.first_name}}
                    </div>
                  </div>
                  <hr>
                    <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Last Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ profile.user.last_name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Username</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ profile.user.username}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ profile.user.email}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{profile.phoneNumber}}
                    </div>
                  </div>
                </div>
              </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>

            </div>
          </div>
        </div>
    </div>


{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'blog/base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    <style>
    body{

    color: #1a202c;
    text-align: left;
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
    </style>
        <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %})">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center" data-scrollax-parent="true">
      <div class="col-md-7 ftco-animate">
        <span class="subheading">Welcome to StudyLab</span>
        <h1 class="mb-4">User Profile Area </h1>
    </div>
</div>
</div>
</div>
    <div class="container">
    <div class="main-body">

          <!-- Breadcrumb -->
          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">

                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                  <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userForm %}
                            {% bootstrap_form profileForm %}

                            {% buttons %}
                                <button class="btn btn-primary" type="submit">Save</button>
                            {% endbuttons %}
                        </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>
        <br>
        <br>
    </div>


{% endblock %}

accounts/templates/accounts/register.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
{% load bootstrap4 %}

    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %})">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center" data-scrollax-parent="true">
      <div class="col-md-7 ftco-animate">
        <span class="subheading">Welcome to StudyLab</span>
        <h1 style="color:#ce4be8" class="mb-4">Create An Account As Instructor </h1>

    </div>
</div>
</div>
</div>

<section class="ftco-section ftco-no-pb ftco-no-pt">
   <div class="container">
      <div class="row">
         <div class="col-md-7"></div>
         <div class="col-md-5 order-md-last">
          <div class="login-wrap p-4 p-md-5">
              <h3 class="mb-4">Create An New Account </h3>
              <form method="POST" class="signup-form" style="margin-letf">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input class="btn btn-primary submit" type="submit" value="signup">
              </form>
         <p class="text-center">Already Have Account? <a href="{% url 'accounts:userLogin' %}">Sign in </a></p>
     </div>
 </div>
</div>
</div>
</section>

{% endblock %}